{% set version = "1.1.0" %}

package:
  name: mypy-gitlab-code-quality
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mypy-gitlab-code-quality/mypy-gitlab-code-quality-{{ version }}.tar.gz
  sha256: be06b0def23b11f9ba10dda368cdb15f6320b9beb59b02d72642185630ee80e1

build:
  entry_points:
    - mypy-gitlab-code-quality = mypy_gitlab_code_quality:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - mypy_gitlab_code_quality
  commands:
    - pip check
    - which mypy-gitlab-code-quality || where mypy-gitlab-code-quality
  requires:
    - pip

about:
  home: https://github.com/soul-catcher/mypy-gitlab-code-quality
  summary: Simple script to generate gitlab code quality report from output of mypy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
